import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Bug, Leaf, Download, CheckCircle2, AlertTriangle, Shield } from "lucide-react";
import { toast } from "sonner";
import jsPDF from "jspdf";

interface ResultCardProps {
  imageUrl: string;
  prediction: string;
  cure: string;
  modelType: "fertilizer" | "insect";
}

function parseCure(cure: string) {
  const sections: { icon: React.ReactNode; title: string; content: string }[] = [];
  
  const whatMatch = cure.match(/🔍\s*What is it\??\s*\n([\s\S]*?)(?=⚠️|💊|🛡️|$)/i);
  const severityMatch = cure.match(/⚠️\s*How bad is it\??\s*\n([\s\S]*?)(?=💊|🛡️|$)/i);
  const treatmentMatch = cure.match(/💊\s*What to do:?\s*\n([\s\S]*?)(?=🛡️|$)/i);
  const preventMatch = cure.match(/🛡️\s*How to prevent it:?\s*\n([\s\S]*?)$/i);

  if (whatMatch) sections.push({ icon: <CheckCircle2 className="h-5 w-5 text-primary" />, title: "What is it?", content: whatMatch[1].trim() });
  if (severityMatch) sections.push({ icon: <AlertTriangle className="h-5 w-5 text-warning" />, title: "How bad is it?", content: severityMatch[1].trim() });
  if (treatmentMatch) sections.push({ icon: <Leaf className="h-5 w-5 text-primary" />, title: "What to do", content: treatmentMatch[1].trim() });
  if (preventMatch) sections.push({ icon: <Shield className="h-5 w-5 text-accent" />, title: "Prevention", content: preventMatch[1].trim() });

  return sections;
}

export default function ResultCard({ imageUrl, prediction, cure, modelType }: ResultCardProps) {
  const [activeTab, setActiveTab] = useState<"overview" | "treatment">("overview");

  const sections = parseCure(cure);
  const hasSections = sections.length > 0;

  const handleDownloadPDF = async () => {
    try {
      const doc = new jsPDF();
      doc.setFontSize(20);
      doc.setTextColor(34, 120, 60);
      doc.text("Agro AI - Prediction Report", 20, 25);

      doc.setFontSize(12);
      doc.setTextColor(100, 100, 100);
      doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 35);
      doc.text(`Model: ${modelType === "fertilizer" ? "Fertilizer / Disease" : "Insect / Pesticide"}`, 20, 42);

      doc.setDrawColor(34, 120, 60);
      doc.line(20, 48, 190, 48);

      try {
        const imgResp = await fetch(imageUrl);
        const blob = await imgResp.blob();
        const reader = new FileReader();
        const dataUrl = await new Promise<string>((resolve) => {
          reader.onload = () => resolve(reader.result as string);
          reader.readAsDataURL(blob);
        });
        doc.addImage(dataUrl, "JPEG", 20, 55, 80, 60);
      } catch {
        doc.text("[Image could not be loaded]", 20, 75);
      }

      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text("Detected Issue:", 20, 125);
      doc.setFontSize(12);
      doc.setTextColor(50, 50, 50);
      const predLines = doc.splitTextToSize(prediction, 170);
      doc.text(predLines, 20, 133);

      const cureY = 133 + predLines.length * 7 + 10;
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text("Recommended Treatment:", 20, cureY);
      doc.setFontSize(11);
      doc.setTextColor(50, 50, 50);
      const cleanCure = cure.replace(/[🔍⚠️💊🛡️]/gu, "").trim();
      const cureLines = doc.splitTextToSize(cleanCure, 170);
      doc.text(cureLines, 20, cureY + 8);

      doc.setFontSize(9);
      doc.setTextColor(150, 150, 150);
      doc.text("Generated by Agro AI Assistant", 20, 285);

      doc.save(`agro-ai-report-${Date.now()}.pdf`);
      toast.success("PDF downloaded!");
    } catch {
      toast.error("Failed to generate PDF");
    }
  };

  return (
    <Card className="overflow-hidden animate-in slide-in-from-bottom-4 duration-500">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <CardTitle className="text-lg flex items-center gap-2">
            {modelType === "fertilizer" ? (
              <Leaf className="h-5 w-5 text-primary" />
            ) : (
              <Bug className="h-5 w-5 text-warning" />
            )}
            Prediction Result
          </CardTitle>
          <Badge variant={modelType === "fertilizer" ? "default" : "secondary"}>
            {modelType === "fertilizer" ? "Disease" : "Pest"}
          </Badge>
        </div>

        {/* Tabs */}
        <div className="flex gap-1 mt-3 bg-muted rounded-lg p-1">
          <button
            onClick={() => setActiveTab("overview")}
            className={`flex-1 text-sm py-1.5 px-3 rounded-md font-medium transition-all ${
              activeTab === "overview" ? "bg-background text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground"
            }`}
          >
            Overview
          </button>
          <button
            onClick={() => setActiveTab("treatment")}
            className={`flex-1 text-sm py-1.5 px-3 rounded-md font-medium transition-all ${
              activeTab === "treatment" ? "bg-background text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground"
            }`}
          >
            Treatment
          </button>
        </div>
      </CardHeader>

      <CardContent className="space-y-4">
        {activeTab === "overview" ? (
          <>
            <div className="relative rounded-lg overflow-hidden">
              <img src={imageUrl} alt="Analyzed crop" className="w-full h-48 object-cover" />
              <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/60 to-transparent p-4">
                <p className="text-white font-semibold text-lg">{prediction}</p>
              </div>
            </div>

            {hasSections && sections.slice(0, 2).map((s, i) => (
              <div key={i} className="flex gap-3 p-3 rounded-lg bg-muted/50 animate-in fade-in duration-300" style={{ animationDelay: `${i * 100}ms` }}>
                {s.icon}
                <div>
                  <p className="text-sm font-semibold mb-0.5">{s.title}</p>
                  <p className="text-sm text-muted-foreground leading-relaxed">{s.content}</p>
                </div>
              </div>
            ))}

            {!hasSections && (
              <div className="p-3 rounded-lg bg-muted/50">
                <p className="text-sm leading-relaxed whitespace-pre-wrap">{cure}</p>
              </div>
            )}
          </>
        ) : (
          <div className="space-y-3">
            {hasSections ? sections.slice(2).map((s, i) => (
              <div key={i} className="p-4 rounded-lg border border-border bg-card animate-in fade-in duration-300" style={{ animationDelay: `${i * 100}ms` }}>
                <div className="flex items-center gap-2 mb-2">
                  {s.icon}
                  <p className="font-semibold text-sm">{s.title}</p>
                </div>
                <div className="text-sm text-muted-foreground leading-relaxed whitespace-pre-wrap pl-7">
                  {s.content}
                </div>
              </div>
            )) : (
              <div className="p-4 rounded-lg border border-border">
                <p className="text-sm leading-relaxed whitespace-pre-wrap">{cure}</p>
              </div>
            )}

            {hasSections && sections.slice(0, 2).length > 0 && (
              <div className="p-3 rounded-lg bg-muted/30">
                <p className="text-xs text-muted-foreground">
                  💡 Tip: Go to the Overview tab to see what was detected and its severity.
                </p>
              </div>
            )}
          </div>
        )}

        <div className="flex gap-2 pt-2 border-t border-border">
          <Button variant="outline" size="sm" onClick={handleDownloadPDF} className="flex-1">
            <Download className="h-4 w-4 mr-2" />
            Download PDF
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
